---
- hosts: microplat
 
  tasks:
  - name: update apt
    apt: update_cache=yes

  - name: install xinetd packages
    apt:
      pkg:      
       - xinetd
      state: present   

  - name: download the check_mk agent
    get_url: url=http://monitor.wapsite.com/binbit/check_mk/agents/check-mk-agent_1.5.0p7-1_all.deb dest=/tmp/

  - name: install the agent into the server
    apt:
     deb: /tmp/check-mk-agent_1.5.0p7-1_all.deb     
