#VERSION: 0.0.3

---
- hosts: microplat
  #sudo: yes

  vars_files:
    - vars.yml

  tasks:
  - name: update apt
    apt: update_cache=yes

  - name: ensure packages installed 
    apt:
      pkg:       
        - make
        - build-essential
        - tcl8.5
      state: present    

  - name: download latest stable redis
    get_url: url=http://download.redis.io/redis-stable.tar.gz dest=/tmp/redis-stable.tar.gz

  - name: untar redis
    command: tar zxf /tmp/redis-stable.tar.gz -C /tmp

  - name: build redis
    command: make -C /tmp/redis-stable

  - name: create redis group
    group: name=redis state=present system=yes

  - name: create redis user
    user: name=redis group=redis createhome=no shell=/bin/false system=yes state=present

  - name: make sure that /etc/redis exists
    file: path=/etc/redis state=directory mode=0755

  - name: make sure that /var/lib/redis exists
    file: path=/var/lib/redis state=directory mode=0755 group=redis owner=redis

  - name: make sure redis.log file exists
    copy: src=/etc/ansible/ansible-sysadmin/templates/redis.log dest=/var/log/redis.log owner=redis group=redis mode=0644

  - name: copy upstart file
    copy: src=/etc/ansible/ansible-sysadmin/templates/upstart.conf dest=/etc/systemd/system/redis.service  

  - name: copy redis.conf file
    copy: src=/etc/ansible/ansible-sysadmin/templates/redis.conf dest=/etc/redis/redis.conf group=redis owner=redis

  - name: copy custom template
    template: src=/etc/ansible/ansible-sysadmin/templates/redis.local.conf.j2 dest=/etc/redis/redis.local.conf group=redis owner=redis

  - name: copy redis-local script
    template: src=/etc/ansible/ansible-sysadmin/templates/redis-local.j2 dest=/usr/local/bin/redis-local mode=0755

  - name: installing redis binaries
    command: cp /tmp/redis-stable/src/{{ item }} /usr/local/bin
    with_items: 
      - redis-server
      - redis-cli
      - redis-check-aof

 # - name: ensure redis service is restarted
 #   service: name=redis state=restarted
 #   become: true

